-- A股股票分析系统 PostgreSQL Schema
-- Supabase / Postgres. Backend writes should use the Session Pooler URL.

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    phone TEXT,
    nickname TEXT,
    avatar_url TEXT,
    role TEXT DEFAULT 'free' CHECK (role IN ('free', 'pro', 'admin')),
    credits INTEGER DEFAULT 10,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    last_login_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS user_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token TEXT UNIQUE NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS stock_cache (
    code TEXT NOT NULL,
    date TEXT NOT NULL,
    open DOUBLE PRECISION,
    high DOUBLE PRECISION,
    low DOUBLE PRECISION,
    close DOUBLE PRECISION,
    volume DOUBLE PRECISION,
    pe_ratio DOUBLE PRECISION,
    pb_ratio DOUBLE PRECISION,
    market_cap DOUBLE PRECISION,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (code, date)
);

CREATE TABLE IF NOT EXISTS analysis_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    stock_code TEXT NOT NULL,
    stock_name TEXT,
    ma5 DOUBLE PRECISION,
    ma10 DOUBLE PRECISION,
    ma20 DOUBLE PRECISION,
    ma60 DOUBLE PRECISION,
    macd DOUBLE PRECISION,
    macd_signal DOUBLE PRECISION,
    macd_hist DOUBLE PRECISION,
    kdj_k DOUBLE PRECISION,
    kdj_d DOUBLE PRECISION,
    kdj_j DOUBLE PRECISION,
    rsi DOUBLE PRECISION,
    boll_upper DOUBLE PRECISION,
    boll_mid DOUBLE PRECISION,
    boll_lower DOUBLE PRECISION,
    pe_ratio DOUBLE PRECISION,
    pb_ratio DOUBLE PRECISION,
    recent_change_5d DOUBLE PRECISION,
    recent_change_20d DOUBLE PRECISION,
    volume_ratio DOUBLE PRECISION,
    tech_score DOUBLE PRECISION,
    fundamental_score DOUBLE PRECISION,
    total_score DOUBLE PRECISION,
    recommendation TEXT,
    analysis_text TEXT,
    buy_date TEXT,
    cost_price DOUBLE PRECISION,
    strategy_exit_json JSONB,
    sector_name TEXT,
    sector_type TEXT,
    sector_rank INTEGER,
    sector_score DOUBLE PRECISION,
    sector_heat DOUBLE PRECISION,
    sector_change_pct DOUBLE PRECISION,
    sector_heat_window TEXT,
    sector_heat_date TEXT,
    sector_source TEXT,
    sector_confidence DOUBLE PRECISION,
    sector_context_json TEXT,
    retail_direction TEXT,
    retail_score DOUBLE PRECISION,
    flow_recommendation TEXT,
    exit_risk_score DOUBLE PRECISION,
    strategy_risk_level TEXT,
    strategy_risk_score DOUBLE PRECISION,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS watchlist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    stock_code TEXT NOT NULL,
    stock_name TEXT,
    added_at TIMESTAMPTZ DEFAULT NOW(),
    pinned_at TIMESTAMPTZ,
    UNIQUE (user_id, stock_code)
);

CREATE TABLE IF NOT EXISTS strategy_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    strategy_key TEXT NOT NULL,
    trade_date TEXT NOT NULL,
    status TEXT NOT NULL,
    started_at TIMESTAMPTZ DEFAULT NOW(),
    finished_at TIMESTAMPTZ,
    total_scanned INTEGER DEFAULT 0,
    total_picks INTEGER DEFAULT 0,
    error TEXT,
    UNIQUE (strategy_key, trade_date)
);

CREATE TABLE IF NOT EXISTS strategy_recommendations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id BIGINT NOT NULL REFERENCES strategy_runs(id) ON DELETE CASCADE,
    strategy_key TEXT NOT NULL,
    code TEXT NOT NULL,
    name TEXT,
    rank INTEGER,
    score DOUBLE PRECISION,
    mode TEXT,
    reasons_json TEXT,
    risks_json TEXT,
    metrics_json TEXT,
    data_status_json TEXT,
    sector_name TEXT,
    sector_type TEXT,
    sector_rank INTEGER,
    sector_score DOUBLE PRECISION,
    sector_heat DOUBLE PRECISION,
    sector_change_pct DOUBLE PRECISION,
    sector_heat_window TEXT,
    sector_heat_date TEXT,
    sector_source TEXT,
    sector_confidence DOUBLE PRECISION,
    sector_context_json TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS attention_heat_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_date TEXT,
    snapshot_ts DOUBLE PRECISION,
    snapshot_json JSONB NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS user_quant_strategies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    platform TEXT DEFAULT 'python_joinquant',
    source_code TEXT NOT NULL,
    source_hash TEXT NOT NULL,
    parse_status TEXT NOT NULL DEFAULT 'pending',
    parse_result_json JSONB,
    ai_status TEXT NOT NULL DEFAULT 'disabled',
    ai_analysis_json JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    last_analyzed_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_tokens_user ON user_tokens(user_id);
CREATE INDEX IF NOT EXISTS idx_tokens_token ON user_tokens(token);
CREATE INDEX IF NOT EXISTS idx_cache_code ON stock_cache(code);
CREATE INDEX IF NOT EXISTS idx_analysis_user ON analysis_history(user_id);
CREATE INDEX IF NOT EXISTS idx_analysis_code ON analysis_history(stock_code);
CREATE INDEX IF NOT EXISTS idx_analysis_time ON analysis_history(created_at);
CREATE INDEX IF NOT EXISTS idx_watchlist_user ON watchlist(user_id);
CREATE INDEX IF NOT EXISTS idx_strategy_runs_date ON strategy_runs(trade_date);
CREATE INDEX IF NOT EXISTS idx_strategy_runs_key_date ON strategy_runs(strategy_key, trade_date);
CREATE INDEX IF NOT EXISTS idx_strategy_recommendations_run ON strategy_recommendations(run_id);
CREATE INDEX IF NOT EXISTS idx_attention_heat_snapshots_date ON attention_heat_snapshots(snapshot_date);
CREATE INDEX IF NOT EXISTS idx_user_quant_strategies_user ON user_quant_strategies(user_id);

ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE stock_cache ENABLE ROW LEVEL SECURITY;
ALTER TABLE analysis_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE watchlist ENABLE ROW LEVEL SECURITY;
ALTER TABLE strategy_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE strategy_recommendations ENABLE ROW LEVEL SECURITY;
ALTER TABLE attention_heat_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_quant_strategies ENABLE ROW LEVEL SECURITY;
